export interface BrandFaq { q: string; a: string }

export interface Brand {
  slug: string
  name: string
  metaTitle: string
  metaDesc: string
  h1: string
  postcode: string
  intro: string
  keyTech: string
  models: string[]
  pricingRows: [string, string][]
  faqs: BrandFaq[]
}

export const brands: Brand[] = [
  {
    slug: 'ford',
    name: 'Ford',
    metaTitle: 'Ford Car Key Replacement Leeds | All Models | 07309 903243',
    metaDesc: 'Mobile Ford car key specialist in Leeds. Fiesta, Focus, Kuga, Puma, Transit — cut and programmed on-site. 24/7, fixed price. Call 07309 903243.',
    h1: 'Ford Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: 'Ford is the most common vehicle on Leeds roads — from the Fiesta on Beeston terraces to the Transit on Middleton trading estates. We carry Ford key blanks and PATS programming data for every current and recent Ford model, meaning the vast majority of Ford jobs in Leeds are completed in a single visit without ordering parts.',
    keyTech: 'Ford uses its Passive Anti-Theft System (PATS) across all models from the late 1990s onwards. Newer Fords — Puma, Kuga, and Transit Custom from 2018 onward — use the Passive Entry Passive Start (PEPS) proximity system, which requires specialist EEPROM-level programming. We carry the Ford-specific diagnostic interface and key blanks for all PATS and PEPS variants. All-keys-lost jobs on Ford are handled via pin-code extraction from the ECU — no towing to a dealer required.',
    models: ['Ford Fiesta', 'Ford Focus', 'Ford Kuga', 'Ford Puma', 'Ford EcoSport', 'Ford Mondeo', 'Ford Galaxy', 'Ford S-Max', 'Ford Edge', 'Ford Mustang Mach-E', 'Ford Transit', 'Ford Transit Custom', 'Ford Transit Connect', 'Ford Ranger', 'Ford Tourneo'],
    pricingRows: [
      ['Ford key replacement (transponder / PATS)', '£80 – £150'],
      ['Ford smart / proximity key (PEPS)', '£160 – £240'],
      ['Ford lockout — emergency access', '£60 – £100'],
      ['Ford spare key — cut + programme', '£80 – £140'],
      ['Ford Transit van key replacement', '£90 – £160'],
    ],
    faqs: [
      { q: 'How much does a Ford key replacement cost in Leeds?', a: 'A Ford transponder key (Fiesta, Focus, older Kuga) costs £80–£150 cut and programmed on-site in Leeds. Smart proximity keys on newer Puma, Kuga, and Transit Custom models cost £160–£240. The price is fixed and confirmed over the phone before we travel — no surprises on arrival.' },
      { q: 'Can you replace a Ford key without going to a dealer?', a: 'Yes. We programme Ford keys using the same PIN-code extraction process dealers use, but at your location. For PATS-equipped Fords (most models up to 2018), the job takes 45–60 minutes. For PEPS proximity keys on newer models, allow 60–75 minutes. No towing, no waiting days for a dealer appointment.' },
      { q: 'What do you do if I have lost all my Ford keys?', a: "All-keys-lost on a Ford requires extracting the security PIN from the vehicle's ECU before a new key can be programmed. We carry the specialist Ford interface to do this on-site. Once the PIN is extracted, we cut a new key blank and programme it to the PATS or PEPS system. Expect 60–90 minutes for a complete all-keys-lost Ford job." },
      { q: 'Do you cover Ford Transit and Transit Custom vans?', a: 'Yes. Transit and Transit Custom are among our most common commercial call-outs in Leeds. We carry blanks for all Transit variants including the Connect, Custom, and full-size Transit. Transit Custom from 2018 uses proximity entry — we carry the programming equipment for this too. Van jobs start from £90.' },
      { q: 'How long does a Ford key replacement take?', a: 'Standard PATS key (Fiesta, Focus, Mondeo): 45–60 minutes from arrival. PEPS proximity key (Puma, newer Kuga, Transit Custom): 60–75 minutes. All-keys-lost: 60–90 minutes. We give you a realistic time estimate when you call so you know what to expect.' },
      { q: 'My Ford Fiesta key fob has stopped working — what does that mean?', a: "If the key fob buttons stop working but the blade still starts the car, it's usually a dead fob battery (CR2032, easy to replace) or a failed fob circuit. If neither the fob nor the blade works, the transponder chip may have de-programmed — we can re-synchronise it on-site. If the blade works but the engine won't start, the transponder chip needs re-programming to the ECU." },
      { q: 'Can you make a spare Ford key while I still have my original?', a: 'Yes — and we recommend it. Getting a spare Ford key made while you have the original costs £80–£140 depending on the key type. If you lose the original later and need a full all-keys-lost replacement, the cost rises to £150–£240. Spares can usually be made the same day in Leeds.' },
      { q: 'Do you cover Ford keys in all Leeds areas?', a: 'Yes. We cover all Leeds postcodes — LS1 through LS29, and WF areas on the south Leeds border. We respond to Ford key jobs in Middleton, Beeston, Morley, Rothwell, Armley, Headingley, Roundhay, Garforth, and everywhere in between. Response time is 25–45 minutes across the Leeds area.' },
    ],
  },
  {
    slug: 'vauxhall',
    name: 'Vauxhall',
    metaTitle: 'Vauxhall Car Key Replacement Leeds | Corsa Astra Mokka | 24/7',
    metaDesc: 'Mobile Vauxhall car key specialist Leeds. Corsa, Astra, Mokka, Insignia — transponder key replacement and lockouts. 24/7 fixed price. Call 07309 903243.',
    h1: 'Vauxhall Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: 'Vauxhall remains one of the most popular brands across South and West Leeds — Corsa and Astra are a constant in our call-outs from Beeston to Morley. We carry Vauxhall key blanks and ID40/ID46 transponder data for the full Vauxhall range, enabling single-visit completion for the overwhelming majority of jobs.',
    keyTech: 'Vauxhall uses Texas Instruments ID40 transponder chips on older models (Astra G/H, Corsa C/D) and ID46 Megamos Crypto on newer models including Corsa E, Astra K, and Mokka X. The Corsa D and E Ultraflip remote key uses a fixed-code ID46 chip requiring EEPROM dump for all-keys-lost scenarios. Newer Vauxhall Mokka-e and Crossland use the PSA-group BSI unit (shared with Peugeot/Citroën post-2020 collaboration). We carry programming tools and key blanks for all Vauxhall variants sold in the UK.',
    models: ['Vauxhall Corsa', 'Vauxhall Astra', 'Vauxhall Mokka', 'Vauxhall Insignia', 'Vauxhall Grandland', 'Vauxhall Crossland', 'Vauxhall Zafira', 'Vauxhall Meriva', 'Vauxhall Combo', 'Vauxhall Vivaro', 'Vauxhall Movano'],
    pricingRows: [
      ['Vauxhall transponder key (ID40/ID46)', '£80 – £140'],
      ['Vauxhall Ultraflip remote key', '£90 – £150'],
      ['Vauxhall smart key (Mokka-e, Grandland)', '£150 – £220'],
      ['Vauxhall lockout — emergency access', '£60 – £100'],
      ['Vauxhall Vivaro / Movano van key', '£90 – £160'],
    ],
    faqs: [
      { q: 'How much does a Vauxhall key replacement cost in Leeds?', a: 'A standard Vauxhall transponder key (Corsa, Astra) costs £80–£140 cut and programmed on-site. Ultraflip remote keys run £90–£150. Smart keys on newer Mokka-e and Grandland X cost £150–£220. All prices are confirmed over the phone before we travel.' },
      { q: 'Can you replace a Vauxhall Corsa key without a dealer?', a: "Yes. Corsa D and E keys use ID46 Megamos Crypto chips. For jobs where you have an existing working key, we can programme a new one on-site in around 45 minutes. All-keys-lost Corsa jobs require EEPROM extraction from the BSI unit — we carry the equipment to do this roadside or on your driveway." },
      { q: 'My Vauxhall key fob has stopped unlocking the car — is the key broken?', a: "Usually not. The most common cause is a flat CR2032 battery in the fob. Replace it and re-sync by holding the fob buttons. If that doesn't work, the fob remote circuit may have failed — we can replace the fob shell and re-programme it. If the car won't start either, the transponder chip needs re-pairing to the ECU." },
      { q: 'Do you cover Vauxhall Vivaro and Movano vans in Leeds?', a: 'Yes. Vivaro and Movano are among the most common commercial vans in the Leeds area. We carry blanks and programming data for both. Vivaro uses a Renault Trafic-platform key system (ID46), so equipment is shared across the PSA/Renault commercial van group. Van jobs start from £90.' },
      { q: 'How long does a Vauxhall key replacement take?', a: 'Standard transponder or Ultraflip key: 40–55 minutes from arrival. All-keys-lost requiring EEPROM extraction: 60–80 minutes. We give you a time estimate on the call so you are not left guessing.' },
      { q: 'Can you programme a Vauxhall key I bought online?', a: "Rarely — and we advise against it. Vauxhall keys bought on eBay or Amazon are usually pre-programmed or wrong-frequency blanks that cannot be re-programmed to your vehicle's immobiliser. We supply and programme the correct blank as part of the job. You pay for a key that works, not for a blank you have to source separately." },
      { q: 'Do you cover older Vauxhall models like the Astra G and Vectra?', a: 'Yes. Older Vauxhalls with ID40 chips (Astra G, Vectra B/C, Zafira A) are straightforward jobs. Blanks are inexpensive and programming is fast. These models make up a portion of our Morley and Beeston call-outs where older vehicles are still in daily use.' },
      { q: 'Can you help with a Vauxhall lockout in the middle of the night?', a: 'Yes — 24 hours a day, 7 days a week. Vauxhall lockouts are a frequent out-of-hours call. We use non-destructive entry techniques so there is no damage to locks or paintwork. Standard lockout starts from £60 during the day, £70–£100 at night.' },
    ],
  },
  {
    slug: 'volkswagen',
    name: 'Volkswagen',
    metaTitle: 'VW Car Key Replacement Leeds | Golf Polo Tiguan Passat | 24/7',
    metaDesc: 'Mobile VW key specialist in Leeds. Golf, Polo, Tiguan, Passat — ID48 transponder, smart keys cut and programmed on-site. 24/7. Call 07309 903243.',
    h1: 'Volkswagen Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: 'Volkswagen models are among the most common premium-brand vehicles across Leeds — Golf and Polo are ubiquitous from Headingley to Garforth. VW uses the VAG group key system shared with Audi, Seat, and Skoda, which means our VW programming equipment covers the full range from a 2000 Golf IV to the latest ID.4.',
    keyTech: "Volkswagen uses Megamos ID48 transponder chips on models up to around 2016 — Golf V/VI/VII, Polo, Passat B6/B7/B8, Tiguan Mk1. The ID48 system is well-understood and handled on-site. Newer VW models from 2017 onward use the Megamos AES (ID47/AES) system, which requires a more involved EEPROM-level procedure for all-keys-lost scenarios. The latest VW ID series (ID.3, ID.4) uses a digital key system over the MQB platform. We carry VAG-group OBD tools and all VW key blank profiles for UK-market vehicles.",
    models: ['VW Golf', 'VW Polo', 'VW Tiguan', 'VW Passat', 'VW T-Roc', 'VW T-Cross', 'VW Touareg', 'VW Caddy', 'VW Transporter', 'VW Crafter', 'VW ID.3', 'VW ID.4', 'VW Sharan', 'VW Touran'],
    pricingRows: [
      ['VW transponder key (ID48)', '£90 – £160'],
      ['VW smart / comfort key (AES)', '£160 – £250'],
      ['VW lockout — emergency access', '£60 – £100'],
      ['VW spare key — cut + programme', '£90 – £150'],
      ['VW Transporter / Crafter van key', '£100 – £170'],
    ],
    faqs: [
      { q: 'How much does a VW key replacement cost in Leeds?', a: 'A VW ID48 transponder key (Golf, Polo, Passat, Tiguan up to 2016) costs £90–£160 on-site in Leeds. AES smart keys on newer models cost £160–£250. Prices are fixed and confirmed before we travel. VAT receipts provided.' },
      { q: 'Can you replace a VW key without the dealer?', a: "Yes. VW dealer key programming costs £250–£400+ and requires booking days in advance. We use the same OBD-level VAG tools to programme keys on-site in 45–75 minutes. The only scenario that differs is all-keys-lost on an AES-equipped VW (2017+), which requires EEPROM extraction — still done at your location, no towing needed." },
      { q: 'My VW Golf key fob buttons have stopped working — what should I do?', a: "First, try a new CR2032 battery. If that doesn't restore the remote functions, the fob body may be cracked internally (common in worn Golf keys) — we can replace the fob shell and re-pair it. If the car won't start, the transponder chip has lost its pairing and needs re-programming to the ECU, which we do on-site." },
      { q: 'Do you cover VW Transporter and Crafter vans in Leeds?', a: 'Yes. VW Transporter (T5, T6, T6.1) and Crafter are regular commercial call-outs. The T6.1 uses proximity keyless entry — we carry the programming equipment. T5 uses ID48 — straightforward. Crafter shares the Mercedes Sprinter platform from 2017 and uses a corresponding key system. Van keys start from £100.' },
      { q: 'Is a VW ID.3 or ID.4 key replacement different?', a: "VW's ID-series uses the MQB Evo platform with a digital RFID-based key card system. Programming requires the VW ODIS diagnostic software at dealer level — we carry a compatible interface. ID-series all-keys-lost is more involved and costs £220–£300. Call us with your exact VIN and model year and we'll confirm scope before travelling." },
      { q: 'Can you programme a second key for my VW while I still have one?', a: 'Yes — and it is significantly cheaper than a replacement. Adding a second VW key while the original is present costs £90–£150. If the original is later lost and we have to do an all-keys-lost job, cost rises to £160–£250. We can come to your Leeds home or workplace the same day in most cases.' },
      { q: 'Does a VW key replacement cover all functions — remote locking, boot release, alarm?', a: 'Yes. We programme the full key profile including remote central locking, boot release, alarm arm/disarm, and transponder immobiliser bypass. The key is tested on all functions before we leave.' },
      { q: 'How long does a VW key replacement take in Leeds?', a: 'ID48 key (Golf, Polo, Tiguan Mk1): 45–60 minutes. AES smart key (Golf VIII, Tiguan Mk2, T-Roc): 60–75 minutes. All-keys-lost requiring EEPROM: 75–90 minutes. Response time across Leeds is 25–45 minutes from your call.' },
    ],
  },
  {
    slug: 'audi',
    name: 'Audi',
    metaTitle: 'Audi Car Key Replacement Leeds | A3 A4 Q3 Q5 | 24/7 Mobile',
    metaDesc: 'Mobile Audi key specialist Leeds. A3, A4, A6, Q3, Q5 — Megamos AES, smart key programmed on-site. 24/7 fixed price. Call 07309 903243.',
    h1: 'Audi Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: 'Audi owners across Leeds — from the A3 commuters in Headingley to Q5 drivers in Roundhay — know that losing a key or getting locked out can be an expensive and slow dealer experience. We programme Audi keys on-site using VAG-group diagnostic tools, at a fraction of Audi main dealer prices, with same-day availability across all Leeds postcodes.',
    keyTech: 'Audi shares the VAG group key architecture with VW, Seat, and Skoda. Models up to approximately 2016 use Megamos ID48 transponder chips with OBD-level programming. Audi A4 B8/B9, A6 C7/C8, Q5 and Q7 from 2016 onward use Megamos AES encryption (IMMO4/IMMO5) — the hardest VAG system, requiring EEPROM extraction via the instrument cluster or gateway module for all-keys-lost scenarios. Audi Comfort Access (proximity) keys require additional RF pairing on top of the transponder programming. We carry full VAG EEPROM and OBD tooling for all UK-market Audi models.',
    models: ['Audi A1', 'Audi A3', 'Audi A4', 'Audi A5', 'Audi A6', 'Audi A7', 'Audi A8', 'Audi Q2', 'Audi Q3', 'Audi Q5', 'Audi Q7', 'Audi Q8', 'Audi TT', 'Audi e-tron'],
    pricingRows: [
      ['Audi transponder key (ID48 — A3, Q3 pre-2016)', '£110 – £170'],
      ['Audi AES smart key (A4, A6, Q5 2016+)', '£180 – £280'],
      ['Audi Comfort Access proximity key', '£200 – £300'],
      ['Audi lockout — emergency access', '£70 – £110'],
      ['Audi spare key (second key with original present)', '£110 – £200'],
    ],
    faqs: [
      { q: 'How much does an Audi key replacement cost in Leeds?', a: "Audi key costs vary by model and generation. Older models with ID48 (A3 8P, Q3 first-gen): £110–£170. Newer AES-encrypted models (A4 B9, A6 C8, Q5 FY): £180–£280. Comfort Access proximity keys: £200–£300. All prices confirmed over the phone — Audi's complexity means we quote precisely for your specific VIN before travelling." },
      { q: 'Can you replace an Audi key without going to an Audi dealer?', a: "Yes. Audi dealer key programming costs £350–£600+. We use the same VAG-group ODIS diagnostic tools and handle the job at your location in 60–90 minutes for most models. All-keys-lost on IMMO5-equipped Audis requires EEPROM extraction — we carry the adapters to do this on-site without removing the instrument cluster at a workshop." },
      { q: 'What is Audi IMMO5 and why does it affect key replacement cost?', a: "IMMO5 is Audi's latest immobiliser generation, introduced on A4 B9, A6 C8, Q5 (FY), and Q7 (4M) from around 2016. It uses Megamos AES 128-bit encryption — significantly harder to bypass than the earlier ID48 system. All-keys-lost on IMMO5 vehicles requires reading the EEPROM of the instrument cluster or gateway module to extract the CS/PIN. It's a more involved job (75–90 minutes) but entirely possible on-site." },
      { q: 'My Audi Comfort Access key is not detecting the car — what is the problem?', a: "Proximity detection failure on Audi Comfort Access can have several causes: flat fob battery (CR2025), worn antenna in the door handle, or the key losing its RF pairing. We can re-pair the proximity function on-site. If the key also fails to start the car, the transponder has de-programmed and needs a full ECU re-sync." },
      { q: 'Do you cover Audi key replacement in areas like Roundhay, Headingley, and Alwoodley?', a: 'Yes. We cover all Leeds postcodes. Roundhay (LS8), Headingley (LS6), Chapel Allerton (LS7), Alwoodley (LS17), and the north Leeds suburbs are all within our response area. We typically reach north Leeds in 30–45 minutes from our Middleton base.' },
      { q: 'Can you replace an Audi key if I have one working key already?', a: 'Yes — and this is the most cost-effective route. Programming a second Audi key while the original is present avoids the EEPROM extraction step, saving both time and cost. Second key with original present: £110–£200 depending on model. Same-day service across Leeds.' },
      { q: 'Is an Audi e-tron key replacement different from a petrol Audi?', a: "The e-tron uses the MEB/MLB platform with Megamos AES encryption — the same as other late-model Audis. The key programming process is equivalent. Smart key replacement on e-tron: £200–£300. Call us with the VIN and model year and we'll confirm scope before travelling." },
      { q: 'How quickly can you reach me if I am locked out of my Audi in Leeds?', a: 'Response time across Leeds is 25–45 minutes. We cover Audi lockouts using non-destructive entry techniques — no damage to the door seals or locking mechanism. Lockout starts from £70. 24 hours a day, 7 days a week.' },
    ],
  },
  {
    slug: 'bmw',
    name: 'BMW',
    metaTitle: 'BMW Car Key Replacement Leeds | 1 3 5 Series X3 X5 | 24/7',
    metaDesc: 'Mobile BMW key specialist Leeds. 1 Series, 3 Series, X3, X5 — CAS system, Comfort Access, Display Key programmed on-site. 24/7. Call 07309 903243.',
    h1: 'BMW Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: 'BMW drivers in Leeds — whether a 3 Series in Horsforth or an X5 in Alwoodley — face some of the most complex key replacement scenarios of any brand. The BMW CAS (Car Access System) requires specific coding to the vehicle. We carry BMW-specific programming tools and key blanks for all CAS generations, providing a dealer-equivalent service at your location across all Leeds postcodes.',
    keyTech: "BMW uses its Car Access System (CAS) across all modern models. CAS2 covers E-series (E46, E90, E60) up to 2007; CAS3/CAS3+ covers E-series 2007–2013 and F-series from 2010; FEM/BDC module covers F-series 2014+ and early G-series; CAS4 covers G-series 2018+. BMW Comfort Access proximity keys require RF antenna registration in addition to transponder programming. The BMW Display Key (7 Series, X5, X7) has a built-in touchscreen and requires specific NBA protocol programming. All-keys-lost on CAS3+ and newer requires ISN (Individual Serial Number) extraction from the DME/ECU, which we handle on-site.",
    models: ['BMW 1 Series', 'BMW 2 Series', 'BMW 3 Series', 'BMW 4 Series', 'BMW 5 Series', 'BMW 6 Series', 'BMW 7 Series', 'BMW X1', 'BMW X2', 'BMW X3', 'BMW X4', 'BMW X5', 'BMW X6', 'BMW X7', 'BMW M Series'],
    pricingRows: [
      ['BMW transponder key (CAS2/CAS3 — E-series)', '£130 – £200'],
      ['BMW smart key (FEM/CAS4 — F/G-series)', '£200 – £300'],
      ['BMW Comfort Access proximity key', '£200 – £300'],
      ['BMW lockout — emergency access', '£70 – £110'],
      ['BMW spare key (with original present)', '£130 – £220'],
    ],
    faqs: [
      { q: 'How much does a BMW key replacement cost in Leeds?', a: 'BMW key costs depend heavily on the CAS generation. E-series (CAS2/CAS3): £130–£200. F-series with FEM module or G-series with CAS4: £200–£300. Comfort Access or Display Key: £200–£300. Prices confirmed over the phone after we identify your exact model and CAS version — call us with your registration for a precise quote.' },
      { q: 'Can you replace a BMW key without a main dealer?', a: "Yes. BMW dealer key replacement starts at £400 and can reach £600+ for Comfort Access or Display Key. We use BMW-compatible ISTA/ISID diagnostic tools and carry BMW key profiles for all CAS generations. The job is done at your location — no recovery truck, no dealer booking, same-day in most cases." },
      { q: 'What is the BMW CAS system and how does it affect key replacement?', a: "BMW's Car Access System (CAS) is a separate security module that manages key authentication. Every replacement key must be coded to your specific CAS module — it's not a case of cutting a blank and inserting it. Different CAS generations (CAS2, CAS3, CAS3+, FEM, CAS4) require different tools and procedures. We carry equipment for all UK-market BMW CAS generations." },
      { q: 'My BMW key fob has cracked and the buttons don't work — can you fix it?', a: "A cracked or damaged BMW key housing is common, particularly on older 3 Series. We can replace the fob shell and internal circuit board while retaining your existing key blade. If the transponder chip is still intact, re-programming is minimal. If the chip is damaged, we supply a new key blank and programme it fully. Housing replacement from £80; full key replacement from £130." },
      { q: 'Do you cover BMW Comfort Access proximity keys?', a: "Yes. BMW Comfort Access is available on 3 Series F30/G20, 5 Series, X3, X5, and most G-series BMWs. Programming requires pairing both the EWS transponder and the RF proximity receiver. We carry the BMW-specific protocol adapters for Comfort Access on all UK-market models. Cost: £200–£300." },
      { q: 'Can you replace a BMW key for an all-keys-lost situation?', a: "Yes, though it is the most complex BMW job. All-keys-lost on a CAS3+ or newer BMW requires extracting the ISN (Individual Serial Number) from the DME/ECU. We carry the adapters to do this on-site for most F and G-series BMWs. Expect 75–90 minutes and a cost of £250–£350. We need proof of ownership before starting." },
      { q: 'Do you cover BMW X3, X5, and X7 SUVs in Leeds?', a: 'Yes. BMW X-series are regular call-outs in the Roundhay, Alwoodley, and Harrogate Road corridor. The X3 (F25/G01) and X5 (F15/G05) typically use FEM or CAS4 systems. X7 uses CAS4 with optional Display Key. We cover all variants and carry the relevant programming data.' },
      { q: 'How quickly can you reach me with a BMW key emergency in Leeds?', a: 'Response time across Leeds is 25–45 minutes. We cover all Leeds postcodes — from city centre LS1 to the outer suburbs LS17, LS29. We call you when 10 minutes away. 24/7.' },
    ],
  },
  {
    slug: 'mercedes',
    name: 'Mercedes',
    metaTitle: 'Mercedes Car Key Replacement Leeds | A C E Class GLC | 24/7',
    metaDesc: 'Mobile Mercedes key specialist Leeds. A-Class, C-Class, E-Class, GLC — NEC chip, Keyless Go programmed on-site. 24/7 fixed price. Call 07309 903243.',
    h1: 'Mercedes Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: 'Mercedes-Benz is a common sight on Leeds roads from city centre to outer suburbs — the C-Class and A-Class especially. Mercedes key systems are among the more security-conscious on the market, using NEC/Siemens chips and infra-red data transfer on older models. We carry Mercedes-specific programming equipment for all UK-market models from W203 onward.',
    keyTech: "Mercedes uses NEC (Nippon Electric Company) microprocessor chips in their key transponders. Older models (W203 C-Class, W211 E-Class, W163 ML) use infra-red key communication — these require the key to be pointed at the dashboard IR reader for programming. From around 2008, Mercedes moved to standard OBD-port programming. Keyless Go (proximity entry) was introduced broadly from 2010 and requires additional ESL (Electronic Steering Lock) synchronisation on some models. All-keys-lost on Mercedes often requires EEPROM reading of the EZS (ignition module) — we carry the ESL bypass and EZS adapters for on-site work.",
    models: ['Mercedes A-Class', 'Mercedes B-Class', 'Mercedes C-Class', 'Mercedes E-Class', 'Mercedes S-Class', 'Mercedes GLA', 'Mercedes GLB', 'Mercedes GLC', 'Mercedes GLE', 'Mercedes GLS', 'Mercedes CLA', 'Mercedes CLS', 'Mercedes Vito', 'Mercedes Sprinter', 'Mercedes Citan'],
    pricingRows: [
      ['Mercedes transponder key (NEC chip — W203/W211)', '£120 – £190'],
      ['Mercedes smart / Keyless Go key', '£190 – £290'],
      ['Mercedes lockout — emergency access', '£70 – £110'],
      ['Mercedes spare key (with original present)', '£120 – £210'],
      ['Mercedes Sprinter / Vito van key', '£100 – £170'],
    ],
    faqs: [
      { q: 'How much does a Mercedes key replacement cost in Leeds?', a: "Mercedes transponder key (C-Class, E-Class, older models): £120–£190. Smart / Keyless Go key (newer A-Class, GLC, C-Class W205/W206): £190–£290. Prices confirmed over the phone once we identify your model and year — Mercedes has significant variation between generations." },
      { q: 'Can you replace a Mercedes key without going to a Mercedes dealer?', a: "Yes. Mercedes dealer key replacement starts at £400 for a basic key, rising to £700+ for Keyless Go. We programme Mercedes keys on-site using NEC/EEPROM tools and genuine-spec key blanks. Most Mercedes key jobs in Leeds take 60–80 minutes at your location." },
      { q: 'What is the infra-red key system on older Mercedes?', a: "Models like the W203 C-Class and W211 E-Class use an infra-red data link between the key and the dashboard receiver to programme new keys. The key must be held at a specific angle near the steering column IR sensor during programming — we carry the correct equipment and procedure for all IR-based Mercedes models. It is less common now but we still get calls for W203s in daily use." },
      { q: 'My Mercedes Keyless Go is not detecting my approach — what is wrong?', a: "Keyless Go detection failure can mean: flat key battery, de-programmed proximity function (needs RF re-pairing), or a failed antenna in the door handle. We can diagnose and fix all three on-site. If the car also refuses to start, the EZS ignition module may have lost sync with the key — that requires a deeper EEPROM-level fix." },
      { q: 'Do you cover Mercedes Sprinter and Vito vans in Leeds?', a: "Yes. Sprinter and Vito are frequent commercial call-outs in the Leeds area. The Sprinter uses NEC chips across most generations; the 2018+ Sprinter shares the VW Crafter platform with a corresponding VW-derived key system. Vito W447 uses a proximity entry system. Van keys start from £100." },
      { q: 'Can you replace a Mercedes key in an all-keys-lost situation?', a: "Yes. All-keys-lost on a Mercedes requires reading the CS/PIN from the EZS module, often via EEPROM extraction. For W204/W205 C-Class and W212/W213 E-Class, we carry the on-car EEPROM adapters. This avoids removing the EZS at a workshop. Expect 75–90 minutes. Cost: £220–£350 depending on model." },
      { q: 'Is a Mercedes A-Class key replacement the same as a C-Class?', a: "The current A-Class (W177) uses a different key system than the C-Class (W205/W206). W177 A-Class uses a proximity smart key with NEC chip and OBD programming. C-Class W205 is similar. W206 C-Class uses the latest VVDI/EEPROM system. We handle all three — call with your registration for a model-specific quote." },
      { q: 'How long does a Mercedes key replacement take in Leeds?', a: 'Standard NEC transponder key: 55–70 minutes. Smart / Keyless Go key: 65–80 minutes. All-keys-lost: 75–90 minutes. Response time across Leeds is 25–45 minutes.' },
    ],
  },
  {
    slug: 'toyota',
    name: 'Toyota',
    metaTitle: 'Toyota Car Key Replacement Leeds | Yaris Corolla RAV4 | 24/7',
    metaDesc: 'Mobile Toyota key specialist Leeds. Yaris, Corolla, RAV4, C-HR — ID67/ID4D transponder and Smart Key programmed on-site. 24/7. Call 07309 903243.',
    h1: 'Toyota Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Toyota's reputation for reliability extends to their key systems — which are generally well-understood and straightforward to programme on-site. Yaris and Corolla are among the most common Toyota call-outs we handle across Leeds, from city centre car parks to suburban driveways in Seacroft and Roundhay.",
    keyTech: "Toyota uses ID4D (80-bit) transponder chips on older models (Yaris, Corolla pre-2016) and ID67 (128-bit AES) on newer models including the Yaris GR, Corolla E210, C-HR, and RAV4 (2018+). Toyota's Smart Key system (proximity entry) uses an encrypted rolling code that requires OBD-level pairing beyond simple transponder programming. All-keys-lost Toyota jobs require pin-code extraction via OBD or the Smart Key ECU — we carry Toyota-specific diagnostic interfaces for all UK-market generations.",
    models: ['Toyota Yaris', 'Toyota Corolla', 'Toyota Aygo', 'Toyota C-HR', 'Toyota RAV4', 'Toyota Prius', 'Toyota Camry', 'Toyota Land Cruiser', 'Toyota Hilux', 'Toyota Proace'],
    pricingRows: [
      ['Toyota transponder key (ID4D)', '£85 – £140'],
      ['Toyota Smart Key (ID67 AES)', '£150 – £220'],
      ['Toyota lockout — emergency access', '£60 – £100'],
      ['Toyota spare key (with original present)', '£85 – £150'],
    ],
    faqs: [
      { q: 'How much does a Toyota key replacement cost in Leeds?', a: 'Toyota ID4D transponder key (Yaris, older Corolla, Auris): £85–£140. Smart Key on newer models (C-HR, RAV4 2018+, Corolla E210): £150–£220. Prices confirmed over the phone based on your model and year.' },
      { q: 'Can you replace a Toyota key without a dealer?', a: "Yes. Toyota dealer key replacement costs £250–£450. We programme Toyota keys on-site using Toyota-compatible OBD tools. Smart Key jobs require pin-code extraction via OBD — we carry the interface for this and complete most jobs in 45–70 minutes at your location." },
      { q: 'Do you cover Toyota hybrids — Prius, Yaris Hybrid, RAV4 Hybrid?', a: "Yes. The key system on Toyota hybrids is the same as the equivalent petrol model — the hybrid drivetrain doesn't affect key programming. Prius (XW30/XW50) uses Toyota Smart Key. Yaris Hybrid (XP210) uses ID67 AES. Same procedures, same costs." },
      { q: 'My Toyota Smart Key is not being detected by the car — what should I check?', a: "First check the fob battery (CR2032). If the car still doesn't detect proximity, the key may have lost its RF pairing — we can re-pair it on-site in 20–30 minutes. If the car also refuses to start, the transponder has de-linked and needs a full OBD re-programme." },
      { q: 'Can you replace a Toyota Aygo key in Leeds?', a: "Yes. Aygo uses a Citroen/Peugeot PSA-platform key (shared development with C1 and 107/108) — a simple remote key with ID46 transponder. One of the more straightforward Toyota jobs. Cost: £85–£130." },
      { q: 'How long does a Toyota key replacement take?', a: 'ID4D key: 40–55 minutes. Smart Key (ID67 AES): 55–70 minutes. Response time across Leeds: 25–45 minutes.' },
      { q: 'Do you cover Toyota Proace and Hilux commercial vehicles?', a: "Yes. Proace shares the PSA/Stellantis platform (same as Peugeot Expert, Citroën Dispatch) and uses PSA group key systems. Hilux uses Toyota's standard ID4D/ID67 system. Both are covered." },
      { q: 'What proof of ownership do you need to replace a Toyota key in Leeds?', a: "We need evidence linking you to the vehicle before cutting or programming any key. V5C logbook, valid insurance document showing your name and the registration, or a finance agreement are all accepted. For lockouts, driver's licence plus any document with the registered keeper name is sufficient." },
    ],
  },
  {
    slug: 'nissan',
    name: 'Nissan',
    metaTitle: 'Nissan Car Key Replacement Leeds | Qashqai Juke Micra | 24/7',
    metaDesc: 'Mobile Nissan key specialist Leeds. Qashqai, Juke, Micra, Note — ID46, Intelligent Key programmed on-site. 24/7 fixed price. Call 07309 903243.',
    h1: 'Nissan Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Nissan Qashqai is one of the top three most common vehicles we work on across Leeds — particularly in the LS10, LS26, and LS27 postcodes. Nissan's Intelligent Key system is well-represented in our programming database, and we carry Nissan key blanks for all current UK models.",
    keyTech: "Nissan uses Philips ID46 transponder chips across most of their range from 2001 onward. Older Micra (K11) and Primera (P10/P11) used simpler Texas Instruments chips. Nissan's Intelligent Key proximity system (available on Qashqai from 2007, Juke from 2010, and all current models) uses an encrypted ID46 with rolling code RF — requiring pin-code extraction via OBD for all-keys-lost scenarios. The Nissan Leaf uses a dedicated EV key system on the same OBD platform. We carry Nissan-specific CONSULT III compatible tools for all programming tasks.",
    models: ['Nissan Qashqai', 'Nissan Juke', 'Nissan Micra', 'Nissan Note', 'Nissan Leaf', 'Nissan X-Trail', 'Nissan Navara', 'Nissan Ariya', 'Nissan NV200', 'Nissan NV300', 'Nissan NV400'],
    pricingRows: [
      ['Nissan transponder key (ID46)', '£85 – £140'],
      ['Nissan Intelligent Key (proximity)', '£140 – £210'],
      ['Nissan lockout — emergency access', '£60 – £100'],
      ['Nissan spare key (with original present)', '£85 – £145'],
      ['Nissan NV200/NV300/NV400 van key', '£90 – £155'],
    ],
    faqs: [
      { q: 'How much does a Nissan Qashqai key replacement cost in Leeds?', a: "Nissan Qashqai key cost depends on generation. J10 (2007–2013) standard remote key: £85–£130. J11 (2014–2021) and J12 (2021+) Intelligent Key proximity: £140–£210. All prices confirmed over the phone — Qashqai is one of our most common jobs so we can usually quote precisely from the registration number alone." },
      { q: 'Can you replace a Nissan key without a dealer?', a: "Yes. Nissan dealer key replacement costs £200–£400. We use Nissan CONSULT-compatible OBD tools and complete most Nissan key jobs in 45–65 minutes at your location. Qashqai, Juke, and Micra are all standard jobs we handle daily across Leeds." },
      { q: 'My Nissan Qashqai Intelligent Key is not being detected — what is the problem?', a: "Intelligent Key detection failure is most often a flat CR2032 battery or the key losing its RF registration. We can re-register the proximity function on-site. If the car also refuses to start, the ID46 transponder has de-programmed — full re-sync via OBD needed. Diagnostic and re-programme takes about 40 minutes." },
      { q: 'Do you cover Nissan Juke key replacement in Leeds?', a: "Yes. Nissan Juke (F15 2010–2019, F16 2019+) uses Intelligent Key on most variants. F15 Juke uses ID46 OBD programming; F16 uses a newer encrypted system. Both handled on-site. Juke key replacement: £140–£210." },
      { q: 'Can you help with a Nissan Leaf key in Leeds?', a: "Yes. The Nissan Leaf (first and second generation) uses a standard Intelligent Key system — the EV drivetrain doesn't change the key programming procedure. Cost is the same as equivalent Nissan models: £140–£210 for a proximity key." },
      { q: 'Do you cover Nissan NV200, NV300, and NV400 vans?', a: "Yes. NV200 (Primastar-based) uses Renault Trafic-platform key system. NV300 is the Vivaro/Trafic platform. NV400 shares with the Vauxhall Movano. All three use ID46-based systems we programme on-site. Van keys start from £90." },
      { q: 'How quickly can you reach me with a Nissan key emergency in Leeds?', a: 'We respond to Nissan call-outs across all Leeds postcodes in 25–45 minutes. Rothwell LS26 and Middleton LS10 — our most common Qashqai call-out areas — are 25–35 minutes from our base.' },
      { q: 'Can you cut a spare Nissan Juke key while I still have my original?', a: "Yes. Second key with original present: £85–£145 depending on model. If the original is later lost, all-keys-lost cost rises to £140–£210. We cover all Leeds postcodes same-day for spare key jobs." },
    ],
  },
  {
    slug: 'renault',
    name: 'Renault',
    metaTitle: 'Renault Car Key Replacement Leeds | Clio Megane Kadjar | 24/7',
    metaDesc: 'Mobile Renault key specialist Leeds. Clio, Megane, Kadjar, Zoe — card key, transponder key programmed on-site. 24/7 fixed price. Call 07309 903243.',
    h1: 'Renault Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Renault's distinctive card key system — used on the Clio III and Megane II and III — is one of the more unique key types we handle. We carry Renault card blanks, standard remote keys, and Hands-Free card data for the full UK Renault range, including the Zoe EV.",
    keyTech: "Renault uses a unique Hands-Free Card key system on Megane II (2002–2008) and Megane III (2008–2015) and Clio III (2005–2012) — a credit-card format RFID key that uses an ID46-derived Renault-specific chip requiring UCHx (Under-dashboard Control Unit) synchronisation. Later Renault models (Clio IV/V, Kadjar, Captur II, Zoe) moved back to standard remote keys with ID46 chips and OBD-level programming. The Zoe uses a keyless entry system shared with the Megane E-Tech platform. We carry Renault UCH tools and OBD interfaces for all generations.",
    models: ['Renault Clio', 'Renault Megane', 'Renault Captur', 'Renault Kadjar', 'Renault Zoe', 'Renault Arkana', 'Renault Scenic', 'Renault Trafic', 'Renault Master', 'Renault Kangoo'],
    pricingRows: [
      ['Renault card key (Megane II/III, Clio III)', '£110 – £170'],
      ['Renault transponder remote key (Clio IV/V, Kadjar)', '£85 – £140'],
      ['Renault Zoe / keyless entry key', '£150 – £220'],
      ['Renault lockout — emergency access', '£60 – £100'],
      ['Renault Trafic / Master van key', '£90 – £155'],
    ],
    faqs: [
      { q: 'How much does a Renault Megane card key replacement cost in Leeds?', a: 'Renault Megane card key (Megane II or III Hands-Free Card) replacement costs £110–£170. This includes the card blank, cutting, and UCH synchronisation. Megane IV and newer use a standard remote key: £85–£140. Prices confirmed over the phone.' },
      { q: 'Can you replace a Renault card key without a dealer?', a: "Yes. Renault dealer card key replacement costs £250–£380. We use Renault-specific UCH synchronisation tools to programme card keys on-site. All-keys-lost on a card-key Megane requires reading the PIN from the UCH module — we carry the adapters for this." },
      { q: 'I lost my Renault Clio III card key — how do I get in and start the car?', a: "Without the card, the Clio III will not start — it uses the card RFID chip for both door access and engine immobiliser. You'll need a replacement card cut and programmed. We can do this at your location in 50–65 minutes. If you have a spare card, present it when you call — having a working spare reduces the time and cost significantly." },
      { q: 'Do you cover Renault Zoe EV key replacement in Leeds?', a: "Yes. The Zoe uses a standard Renault remote key on the ZE50 platform — not a card key. Programming is via OBD. The Zoe's EV drivetrain doesn't affect the key system. Cost: £150–£220 for a keyless entry Zoe key." },
      { q: 'Can you replace a Renault Trafic van key in Leeds?', a: "Yes. Renault Trafic is one of the most common vans in the Leeds commercial area. It shares the PSA/Stellantis X82 platform with the Vauxhall Vivaro and Nissan NV300, using an ID46-based key system. Van key replacement starts from £90." },
      { q: 'What is the UCH in a Renault and why does it matter for key replacement?', a: "UCH stands for Unité de Commande d'Habitacle — Renault's under-dashboard body control module. In card-key Renaults, the UCH stores the key code and controls synchronisation. All-keys-lost jobs require reading the stored code from the UCH EEPROM before a new card can be programmed. We carry the tools to do this on-site." },
      { q: 'How long does a Renault card key replacement take?', a: 'Card key with at least one working spare: 45–55 minutes. All-keys-lost requiring UCH read: 60–75 minutes. Standard remote key (Clio IV+, Kadjar): 40–55 minutes.' },
      { q: 'Do you cover Renault Captur and Kadjar across Leeds?', a: 'Yes — Captur and Kadjar are common South and West Leeds SUV call-outs. Both use standard ID46 remote keys with OBD programming. Captur: £85–£140. Kadjar: £85–£140. Response across all Leeds postcodes: 25–45 minutes.' },
    ],
  },
  {
    slug: 'peugeot',
    name: 'Peugeot',
    metaTitle: 'Peugeot Car Key Replacement Leeds | 208 308 2008 3008 | 24/7',
    metaDesc: 'Mobile Peugeot key specialist Leeds. 208, 308, 2008, 3008, 5008 — BSI module, smart key programmed on-site. 24/7 fixed price. Call 07309 903243.',
    h1: 'Peugeot Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Peugeot is a common choice across Leeds — the 208 and 2008 especially. Peugeot shares the PSA group key architecture with Citroën, meaning our PSA programming tools cover both brands. The BSI (Body Systems Interface) module in PSA group vehicles is central to all key programming — we carry BSI read/write adapters for the full Peugeot range.",
    keyTech: "Peugeot uses the PSA group BSI (Body Systems Interface) as the central key management module. Older models (206, 207, 307, 407) use ID46 Megamos transponders with BSI OBD programming. The 208 first-gen uses an evolving BSI system; the current 208 (B21), 2008 (P24), 308 (P5), and 3008/5008 (P87) use a newer BSI architecture requiring EEPROM extraction for all-keys-lost scenarios. Peugeot e-208 and e-2008 use the PSATEC electric platform with a proximity smart key. We carry PSA ESL/BSI programming tools for all UK-market Peugeot models.",
    models: ['Peugeot 108', 'Peugeot 208', 'Peugeot 308', 'Peugeot 408', 'Peugeot 508', 'Peugeot 2008', 'Peugeot 3008', 'Peugeot 5008', 'Peugeot Partner', 'Peugeot Expert', 'Peugeot Boxer'],
    pricingRows: [
      ['Peugeot transponder key (ID46 BSI)', '£80 – £140'],
      ['Peugeot smart key (current 208/2008/3008)', '£150 – £220'],
      ['Peugeot lockout — emergency access', '£60 – £100'],
      ['Peugeot spare key (with original present)', '£80 – £145'],
      ['Peugeot Partner / Expert van key', '£85 – £150'],
    ],
    faqs: [
      { q: 'How much does a Peugeot key replacement cost in Leeds?', a: 'Peugeot ID46 transponder key (207, 308 first-gen, older 2008): £80–£140. Smart key on current 208/2008/3008/5008: £150–£220. All confirmed over the phone before we travel.' },
      { q: 'What is the BSI module in a Peugeot and why is it important for key replacement?', a: "BSI — Body Systems Interface — is Peugeot's central control module. It stores key codes and manages security. Every new key must be synchronised with the BSI. For all-keys-lost scenarios on newer Peugeots, we must read the BSI EEPROM to extract the stored key data before a new key can be programmed. We carry the on-car BSI EEPROM adapters." },
      { q: 'Can you replace a Peugeot 208 key without a dealer?', a: "Yes. The current Peugeot 208 (B21 platform, 2019+) uses a proximity smart key with BSI EEPROM programming. Dealer cost: £300–£450. We programme it on-site in 55–70 minutes using PSA-specific tools. Fixed price quoted before we travel." },
      { q: 'Do you cover the Peugeot e-208 and e-2008 electric models?', a: "Yes. The e-208 and e-2008 use the PSATEC EV platform with a smart key system equivalent to the petrol versions. Key programming procedure is the same — the electric drivetrain doesn't affect the key system. Cost: £150–£220." },
      { q: 'Can you replace a Peugeot Partner van key in Leeds?', a: "Yes. Partner (K9 platform) uses PSA group BSI system with ID46 transponder — one of the more common commercial van jobs. Partner Tepee and cargo variants use the same system. Van key from £85." },
      { q: 'My Peugeot 3008 key fob isn't being detected by the car — what is wrong?', a: "Check the battery first (CR2032). If proximity detection still fails, the RF pairing may have been lost — we re-pair on-site. If the car also won't start, the BSI has dropped the key's transponder registration and needs a full re-sync via OBD. Takes 45–60 minutes." },
      { q: 'Can you programme a spare Peugeot key in Leeds?', a: "Yes. Spare key with original present: £80–£145 depending on model and key type. Same-day across Leeds. If the original is lost later, all-keys-lost cost rises to £150–£220." },
      { q: 'How long does a Peugeot key job take in Leeds?', a: 'ID46 transponder key: 40–55 minutes. Smart key: 55–70 minutes. All-keys-lost with BSI EEPROM: 65–80 minutes. Response time across Leeds: 25–45 minutes from your call.' },
    ],
  },
  {
    slug: 'hyundai',
    name: 'Hyundai',
    metaTitle: 'Hyundai Car Key Replacement Leeds | Tucson i10 i20 i30 | 24/7',
    metaDesc: 'Mobile Hyundai key specialist Leeds. Tucson, i10, i20, i30, Ioniq — ID60/ID47 transponder and smart key programmed on-site. 24/7. Call 07309 903243.',
    h1: 'Hyundai Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Hyundai has grown significantly in popularity across Leeds — particularly the Tucson SUV and the i10/i20 city cars. Hyundai shares the Hyundai-Kia group key architecture, meaning our programming tools cover both brands with the same equipment. We carry Hyundai key blanks for all current UK-market models.",
    keyTech: "Hyundai uses Texas Instruments ID60 transponder chips on most models from 2010 onward, with ID47 (AES 128-bit) on newer models including the Tucson NX4 (2021+), Ioniq 5, and Ioniq 6. Older Hyundai (i10 IA, i20 PB) use simpler ID46 chips. Hyundai's BlueLink smart key (proximity) is available on Tucson, Santa Fe, and Kona from around 2018 — requiring OBD-level pairing with the SMK (Smart Key) ECU. All-keys-lost Hyundai jobs require pin-code extraction from the immobiliser ECU via OBD.",
    models: ['Hyundai i10', 'Hyundai i20', 'Hyundai i30', 'Hyundai i40', 'Hyundai Tucson', 'Hyundai Santa Fe', 'Hyundai Kona', 'Hyundai Ioniq', 'Hyundai Ioniq 5', 'Hyundai Ioniq 6', 'Hyundai Bayon'],
    pricingRows: [
      ['Hyundai transponder key (ID60)', '£85 – £140'],
      ['Hyundai smart / BlueLink key (ID47)', '£150 – £220'],
      ['Hyundai lockout — emergency access', '£60 – £100'],
      ['Hyundai spare key (with original present)', '£85 – £145'],
    ],
    faqs: [
      { q: 'How much does a Hyundai key replacement cost in Leeds?', a: 'Hyundai ID60 transponder key (i10, i20, i30, older Tucson): £85–£140. Smart / BlueLink key (Tucson NX4, Ioniq 5, Santa Fe): £150–£220. Confirmed over the phone before we travel.' },
      { q: 'Can you replace a Hyundai Tucson key without a dealer?', a: "Yes. The Tucson NX4 (2021+) uses ID47 AES smart key with OBD-level SMK programming. Dealer cost: £280–£420. We programme it at your location in 55–70 minutes using Hyundai-compatible tools. Older Tucson TL (2016–2020) is ID60 OBD — slightly simpler." },
      { q: 'Do you cover Hyundai Ioniq 5 and Ioniq 6 key replacement?', a: "Yes. The Ioniq 5 and Ioniq 6 use the E-GMP electric platform with ID47 smart key programming. The EV drivetrain doesn't affect key replacement. Cost: £150–£220. Call with your exact VIN." },
      { q: 'My Hyundai i20 remote key has stopped working after a battery change — why?', a: "After replacing the battery in a Hyundai remote key, the remote sometimes loses RF sync with the BCM. You can re-sync by sitting in the car, inserting the key, and pressing the lock button for 5 seconds — but if this fails, we re-register the RF function on-site in 20–30 minutes." },
      { q: 'Can you make a spare Hyundai key in Leeds the same day?', a: 'Yes. Spare key with original: £85–£145. We cover all Leeds postcodes same-day. Hyundai blanks are stocked for all current models.' },
      { q: 'Do you cover Hyundai i10 and i20 — older and newer versions?', a: 'Yes. All generations. i10 IA (ID46): £85–£130. i10 BA (ID60): £85–£135. i20 GB/IB (ID60): £85–£140. i20 BC3 (ID47): £140–£200. We carry blanks for all.' },
      { q: 'How long does a Hyundai key replacement take?', a: 'ID60 key: 40–55 minutes. ID47 smart key: 55–70 minutes. All-keys-lost: 60–75 minutes. Response: 25–45 minutes across Leeds.' },
      { q: 'Is a Hyundai Kona key replacement the same as a Tucson?', a: "The Kona OS (2017–2023) uses ID60 on standard variants and ID47 on the Kona N and electric version. Kona SX2 (2023+) uses ID47 across all variants. Tucson TL uses ID60; Tucson NX4 uses ID47. We confirm which system your specific vehicle uses when you call with the registration." },
    ],
  },
  {
    slug: 'kia',
    name: 'Kia',
    metaTitle: 'Kia Car Key Replacement Leeds | Sportage Ceed Niro EV6 | 24/7',
    metaDesc: 'Mobile Kia key specialist Leeds. Sportage, Ceed, Niro, EV6, Picanto — ID60/ID47 transponder and smart key on-site. 24/7 fixed price. Call 07309 903243.',
    h1: 'Kia Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Kia has rapidly become one of the most popular brands in Leeds — the Sportage is a constant sight in South Leeds, and the EV6 is increasingly common. Kia shares the Hyundai-Kia group key system, so our HKG programming tools cover the complete Kia range alongside Hyundai.",
    keyTech: "Kia uses Texas Instruments ID60 transponder chips on models from 2012 onward (Sportage QL, Ceed JD/CD, Picanto JA). Newer Kia models including Sportage NQ5 (2022+), Niro HEV2, EV6, and EV9 use ID47 AES 128-bit encryption. Kia's Smart Key system uses an OBD-level SMK ECU programming procedure identical to the Hyundai equivalent. All-keys-lost requires PIN extraction from the immobiliser module. We carry Kia-compatible HKG diagnostic tools for all generations.",
    models: ['Kia Picanto', 'Kia Rio', 'Kia Ceed', 'Kia Xceed', 'Kia Sportage', 'Kia Niro', 'Kia Stonic', 'Kia Sorento', 'Kia EV6', 'Kia EV9', 'Kia Carnival'],
    pricingRows: [
      ['Kia transponder key (ID60)', '£85 – £140'],
      ['Kia smart key (ID47 — Sportage NQ5, EV6)', '£150 – £220'],
      ['Kia lockout — emergency access', '£60 – £100'],
      ['Kia spare key (with original present)', '£85 – £145'],
    ],
    faqs: [
      { q: 'How much does a Kia Sportage key replacement cost in Leeds?', a: "Kia Sportage QL (2016–2022): ID60 transponder, £85–£140. Sportage NQ5 (2022+): ID47 smart key, £150–£220. Confirmed over the phone based on your registration." },
      { q: 'Can you replace a Kia EV6 key in Leeds?', a: "Yes. The EV6 uses an ID47 smart key on the E-GMP platform. Same programming procedure as Hyundai Ioniq 5. Cost: £150–£220. The EV drivetrain has no bearing on the key system." },
      { q: 'Do you cover older Kia models like the Ceed Mk1 and Sportage SL?', a: "Yes. Sportage SL (2010–2015) uses earlier Kia ID46 system. Ceed JD (2012–2018) uses ID60. Both are standard jobs. Older Kia Picanto SA uses a simpler remote key with Texas Instruments chip. All generations covered." },
      { q: 'My Kia Ceed smart key isn't starting the car — what is the problem?', a: "If the smart key is detected (car recognises proximity) but won't start, the issue is usually the transponder chip de-linking from the ECU — separate from the RF proximity system. We re-programme the transponder on-site. If neither proximity nor start works, full OBD re-sync needed: 50–65 minutes." },
      { q: 'Can you cut a spare Kia key in Leeds the same day?', a: 'Yes. Spare key with original present: £85–£145. Same-day across all Leeds postcodes.' },
      { q: 'How long does a Kia key replacement take?', a: 'ID60 key: 40–55 minutes. ID47 smart key: 55–70 minutes. All-keys-lost: 60–75 minutes. Response: 25–45 minutes across Leeds.' },
      { q: 'Do you cover Kia Niro hybrid and Kia EV9?', a: "Yes. Niro HEV2 (2022+) uses ID47. EV9 uses ID47 on the E-GMP platform. Both handled on-site. Cost: £150–£220." },
      { q: 'I have a Kia with only one key from purchase — should I get a spare?', a: "Absolutely. Getting a spare Kia key while you have the original costs £85–£145. Losing the only key raises the all-keys-lost cost to £150–£220 because we need to extract the PIN from the ECU first. Same-day spare key service across Leeds." },
    ],
  },
  {
    slug: 'honda',
    name: 'Honda',
    metaTitle: 'Honda Car Key Replacement Leeds | Civic CR-V Jazz HR-V | 24/7',
    metaDesc: 'Mobile Honda key specialist Leeds. Civic, CR-V, Jazz, HR-V, ZR-V — Honda G/H chip, smart key programmed on-site. 24/7. Call 07309 903243.',
    h1: 'Honda Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Honda's UK range — Civic, CR-V, Jazz, HR-V — is well-represented across Leeds. Honda uses proprietary transponder chip types that require Honda-specific programming equipment. We carry Honda G and H chip blanks and the Honda-compatible HIM (Honda Interface Module) equivalent for all generations sold in the UK.",
    keyTech: "Honda uses proprietary Honda G (4D60) and Honda H (4D61) transponder chip types — not standard Texas Instruments or Philips chips. These require Honda-specific programming sequences. Older Civic (EP3, FN2), CR-V (RD, RE), and Jazz (GD) use Honda G chips. Current Civic (FL5), CR-V (RW/YH), ZR-V, and Jazz (GK/GR) use Honda H chips or Honda's smart key system with rolling-code RF. All-keys-lost Honda requires pin-extraction via the car's immobiliser ECU — we carry Honda-compatible EEPROM and OBD tools for all UK-market generations.",
    models: ['Honda Jazz', 'Honda Civic', 'Honda CR-V', 'Honda HR-V', 'Honda ZR-V', 'Honda e', 'Honda e:Ny1', 'Honda Accord', 'Honda FR-V'],
    pricingRows: [
      ['Honda transponder key (Honda G/H chip)', '£90 – £150'],
      ['Honda smart key (current Civic/CR-V/ZR-V)', '£155 – £230'],
      ['Honda lockout — emergency access', '£60 – £100'],
      ['Honda spare key (with original present)', '£90 – £150'],
    ],
    faqs: [
      { q: 'How much does a Honda key replacement cost in Leeds?', a: 'Honda transponder key (Jazz, older Civic, older CR-V): £90–£150. Smart key (current Civic FL5, CR-V RW/YH, ZR-V, HR-V RU4): £155–£230. Confirmed over the phone before we travel.' },
      { q: 'Can you replace a Honda key without a Honda dealer?', a: "Yes. We carry Honda G and H chip blanks and Honda-compatible OBD tools. Standard Honda key jobs take 50–65 minutes on-site. Dealer cost for the same job: £250–£400. We handle all Honda models sold in the UK." },
      { q: 'What are Honda G and H transponder chips?', a: "Honda uses proprietary transponder chips rather than standard Philips or Texas Instruments types. The Honda G chip (4D60) is used on older models; the Honda H chip (4D61) is on current models. These require Honda-specific programming equipment — a generic key machine will not programme them correctly. We carry the correct tools and blanks." },
      { q: 'Do you cover the Honda Civic Type R key in Leeds?', a: "Yes. The Civic FL5 Type R uses Honda's smart key with the same H-chip system as the standard FL5 Civic. Programming procedure is the same. Cost: £155–£230." },
      { q: 'Can you replace a Honda Jazz key — older and newer models?', a: "Yes. Jazz GD (2001–2008): Honda G chip, £90–£140. Jazz GE (2008–2015): Honda G chip, £90–£140. Jazz GK (2015–2020): Honda H chip, £90–£150. Jazz GR (2020+): smart key, £155–£230. All generations stocked." },
      { q: 'Do you cover the Honda e and e:Ny1 electric models?', a: "Yes. The Honda e uses a proximity smart key. The e:Ny1 uses Honda's current smart key system. EV drivetrain doesn't change key programming. Cost: £155–£230." },
      { q: 'How long does a Honda key replacement take?', a: 'Honda G/H chip key: 50–65 minutes. Smart key: 60–75 minutes. All-keys-lost: 65–80 minutes. Response across Leeds: 25–45 minutes.' },
      { q: 'Can you cut a spare Honda CR-V key in Leeds?', a: 'Yes. Spare key with original present: £90–£150. Same-day across Leeds. CR-V is a common call-out in North Leeds (Roundhay, Moortown, Alwoodley) where Honda ownership is higher.' },
    ],
  },
  {
    slug: 'seat',
    name: 'Seat',
    metaTitle: 'Seat Car Key Replacement Leeds | Ibiza Leon Ateca Arona | 24/7',
    metaDesc: 'Mobile Seat key specialist Leeds. Ibiza, Leon, Ateca, Arona — ID48 Megamos, smart key programmed on-site. 24/7 fixed price. Call 07309 903243.',
    h1: 'Seat Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Seat shares the VAG group key architecture with VW, Audi, and Skoda — meaning our VAG programming tools handle all Seat models with the same equipment. Ibiza and Leon are popular across Leeds, and we carry Seat key blanks for the full range including the Cupra performance variants.",
    keyTech: "Seat uses Megamos ID48 transponder chips on all models up to approximately 2016 (Ibiza 6J/6F first-gen, Leon 5F first-gen, Ateca KH7 early). Newer Seat models — Ibiza KJ (2018+), Leon KL (2020+), Arona KJ (2018+) — use Megamos AES (ID47) encryption requiring EEPROM-level procedure for all-keys-lost. Cupra Formentor and Born use the AES system. We carry the same full VAG EEPROM and OBD tooling used for VW and Audi, covering all Seat generations sold in the UK.",
    models: ['Seat Ibiza', 'Seat Leon', 'Seat Arona', 'Seat Ateca', 'Seat Tarraco', 'Cupra Formentor', 'Cupra Born', 'Cupra Ateca', 'Seat Alhambra', 'Seat Mii'],
    pricingRows: [
      ['Seat transponder key (ID48)', '£85 – £150'],
      ['Seat smart key (AES — Arona/Ateca/Leon KL)', '£150 – £230'],
      ['Seat lockout — emergency access', '£60 – £100'],
      ['Seat spare key (with original present)', '£85 – £150'],
    ],
    faqs: [
      { q: 'How much does a Seat key replacement cost in Leeds?', a: 'Seat ID48 transponder key (older Ibiza, Leon 5F): £85–£150. AES smart key (Arona, Ateca, Leon KL, Cupra Formentor): £150–£230. Confirmed over the phone.' },
      { q: 'Is a Seat key the same as a VW key?', a: "Seat and VW share the same VAG group key system. The physical key blank differs per model, but the programming procedure and tools are identical. If we can programme a VW Golf key, we can programme a Seat Leon key using the same equipment." },
      { q: 'Can you replace a Cupra Formentor or Cupra Born key?', a: "Yes. Cupra Formentor uses AES smart key system (same as Leon KL). Cupra Born uses the MEB platform with AES key. Both handled on-site. Cost: £150–£230." },
      { q: 'Do you cover older Seat models like the Ibiza 6J and Leon 5F?', a: "Yes. Ibiza 6J (2008–2017) and Leon 5F (2012–2020) use ID48 — standard VAG OBD programming. One of the more straightforward VAG jobs. Cost: £85–£150." },
      { q: 'Can you cut a spare Seat Arona key in Leeds?', a: 'Yes. Spare key with original: £85–£150. Same-day across Leeds for most Seat models.' },
      { q: 'How long does a Seat key replacement take?', a: 'ID48 key: 45–60 minutes. AES smart key: 60–75 minutes. All-keys-lost: 65–85 minutes. Response: 25–45 minutes across Leeds.' },
      { q: 'My Seat Ibiza remote key has stopped working — is the key broken?', a: "Usually a flat CR2032 battery. If replacing the battery doesn't restore remote function, the fob may have lost RF sync — we re-sync on-site. If the car also won't start, the transponder needs re-programming to the ECU." },
      { q: 'Do you cover Seat Alhambra keys in Leeds?', a: "Yes. Alhambra shares the VW Sharan platform and uses the same VAG ID48/AES key system. Cost: £85–£150 for ID48, £150–£230 for AES depending on model year." },
    ],
  },
  {
    slug: 'skoda',
    name: 'Skoda',
    metaTitle: 'Skoda Car Key Replacement Leeds | Octavia Fabia Karoq Kodiaq | 24/7',
    metaDesc: 'Mobile Skoda key specialist Leeds. Octavia, Fabia, Karoq, Kodiaq — ID48/AES transponder and smart key on-site. 24/7. Call 07309 903243.',
    h1: 'Skoda Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Skoda's combination of VAG group engineering and strong value proposition has made models like the Octavia and Karoq extremely popular across Leeds. Skoda shares the VAG group key system entirely with VW, Audi, and Seat — our programming tools are the same, and we carry Skoda key blanks for all UK-market models.",
    keyTech: "Skoda uses Megamos ID48 transponder chips on models up to approximately 2016 — Fabia Mk2/3, Octavia Mk2/3, Yeti. Newer Skoda — Fabia Mk4 (NJ3), Octavia Mk4 (NX), Karoq (NU), Kodiaq (NS) — use Megamos AES (ID47) requiring EEPROM extraction for all-keys-lost. Skoda's Simply Clever philosophy extends to their key blanks — they are often among the most cost-effective in the VAG group. We carry full VAG EEPROM and OBD tooling for all Skoda generations.",
    models: ['Skoda Fabia', 'Skoda Octavia', 'Skoda Scala', 'Skoda Karoq', 'Skoda Kodiaq', 'Skoda Superb', 'Skoda Enyaq', 'Skoda Kamiq', 'Skoda Yeti'],
    pricingRows: [
      ['Skoda transponder key (ID48)', '£85 – £145'],
      ['Skoda smart key (AES — Karoq/Kodiaq/Octavia Mk4)', '£150 – £225'],
      ['Skoda lockout — emergency access', '£60 – £100'],
      ['Skoda spare key (with original present)', '£85 – £145'],
    ],
    faqs: [
      { q: 'How much does a Skoda key replacement cost in Leeds?', a: 'Skoda ID48 key (Fabia Mk2/3, Octavia Mk2/3, Yeti): £85–£145. AES smart key (Octavia Mk4, Karoq, Kodiaq, Fabia Mk4): £150–£225. Confirmed over the phone.' },
      { q: 'Is a Skoda key the same as a VW key?', a: "Yes — same VAG group system. The key blank profiles differ but the programming equipment and process are identical. What we carry for a VW Golf we carry for a Skoda Octavia." },
      { q: 'Can you replace a Skoda Enyaq EV key?', a: "Yes. Enyaq uses the MEB platform with Megamos AES key system — same as VW ID.4. AES smart key: £150–£225. EV drivetrain doesn't affect key programming." },
      { q: 'Do you cover older Skoda Fabia and Octavia models?', a: "Yes. Fabia Mk1/2 (ID48): £85–£140. Octavia Mk1 uses an older Transponder — simpler and cheaper. Octavia Mk2/3 (ID48): £85–£145. All stocked." },
      { q: 'Can you cut a spare Skoda Karoq key in Leeds?', a: 'Yes. Spare key with original: £85–£145. Same-day across Leeds.' },
      { q: 'How long does a Skoda key job take?', a: 'ID48 key: 45–60 minutes. AES smart key: 60–75 minutes. All-keys-lost: 65–85 minutes. Response: 25–45 minutes.' },
      { q: 'My Skoda Octavia flip key blade has snapped — can you fix it?', a: "We can replace the key blade and reprogram a new shell. The internal transponder chip is usually undamaged when the blade breaks. We supply a compatible blank, transfer the chip if intact (or programme a new one), and cut a new blade. Cost starts from £90." },
      { q: 'Do you cover Skoda Superb key replacement in Leeds?', a: "Yes. Superb B8 uses AES smart key system: £150–£225. Superb B6 uses ID48: £85–£145. One of the more spacious VAG vehicles — popular with Leeds families and company car drivers." },
    ],
  },
  {
    slug: 'citroen',
    name: 'Citroën',
    metaTitle: 'Citroën Car Key Replacement Leeds | C3 C4 C5 Berlingo | 24/7',
    metaDesc: 'Mobile Citroën key specialist Leeds. C3, C4, C5 X, Berlingo — BSI module, smart key programmed on-site. 24/7 fixed price. Call 07309 903243.',
    h1: 'Citroën Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Citroën shares the PSA group key architecture with Peugeot — identical BSI (Body Systems Interface) modules, shared key blanks on most models, and the same programming tools. We cover the full Citroën range from the C3 to the Berlingo van, with same-day availability across all Leeds postcodes.",
    keyTech: "Citroën uses PSA group BSI (Body Systems Interface) as the central security module — identical to the Peugeot architecture. C1 (shared with Toyota Aygo and Peugeot 107) uses a simplified ID46 system. C3 (A51/SX), C4 (B7/B41), and C5 X use progressively newer BSI generations requiring EEPROM read for all-keys-lost scenarios on post-2018 models. Berlingo Mk3 (K9) uses the same BSI as the Peugeot Partner — a common and well-understood PSA commercial key. ë-C4 and ë-C3 use the PSATEC EV platform with proximity smart key. We carry PSA BSI read/write tools for all UK-market Citroën generations.",
    models: ['Citroën C1', 'Citroën C3', 'Citroën C4', 'Citroën C5 X', 'Citroën C3 Aircross', 'Citroën C4 Cactus', 'Citroën Berlingo', 'Citroën Dispatch', 'Citroën Relay', 'Citroën SpaceTourer'],
    pricingRows: [
      ['Citroën transponder key (BSI ID46)', '£80 – £140'],
      ['Citroën smart key (BSI EEPROM)', '£150 – £220'],
      ['Citroën lockout — emergency access', '£60 – £100'],
      ['Citroën spare key (with original present)', '£80 – £145'],
      ['Citroën Berlingo / Dispatch van key', '£85 – £150'],
    ],
    faqs: [
      { q: 'How much does a Citroën key replacement cost in Leeds?', a: 'Citroën BSI transponder key (C3, older C4): £80–£140. Smart key on ë-C4, newer C5 X, C4 Mk2: £150–£220. Confirmed over the phone based on your registration.' },
      { q: 'Can you replace a Citroën key without a dealer?', a: "Yes. Citroën dealer key costs £280–£400. We use PSA-specific BSI tools and programme keys at your location in 45–70 minutes. PSA group keys are among our most common jobs — we have high first-visit completion rates for all Citroën models." },
      { q: 'Is a Citroën C3 key the same as a Peugeot 208 key?', a: "The programming procedure and BSI architecture are identical. The physical key blank differs (different shell, different blade cut). But the tools, the BSI pairing method, and the pricing are essentially the same." },
      { q: 'Do you cover the ë-C3 and ë-C4 electric models in Leeds?', a: "Yes. Both use the PSATEC EV platform with proximity smart key. Same BSI programming procedure as the petrol equivalents. Cost: £150–£220." },
      { q: 'Can you replace a Citroën Berlingo van key in Leeds?', a: "Yes. Berlingo K9 (2018+) uses the same PSA BSI system as the Peugeot Partner — a very common commercial call-out. Van key from £85." },
      { q: 'My Citroën C4 key fob has stopped remote-locking the car — what should I do?', a: "Replace the CR2032 battery first. If remote locking still fails, the fob RF has lost sync — we re-sync on-site. If the car also won't start, the BSI has dropped the transponder registration and needs a full OBD re-sync: 45–60 minutes." },
      { q: 'Can you make a spare Citroën C3 key in Leeds?', a: 'Yes. Spare key with original: £80–£140. Same-day across Leeds.' },
      { q: 'How long does a Citroën key job take?', a: 'BSI transponder key: 40–55 minutes. Smart key: 55–70 minutes. All-keys-lost with BSI EEPROM: 65–80 minutes. Response: 25–45 minutes across Leeds.' },
    ],
  },
  {
    slug: 'land-rover',
    name: 'Land Rover',
    metaTitle: 'Land Rover Key Replacement Leeds | Defender Discovery Range Rover',
    metaDesc: 'Mobile Land Rover key specialist Leeds. Defender, Discovery, Range Rover — JLR KVM system, key fob programmed on-site. 24/7. Call 07309 903243.',
    h1: 'Land Rover Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Land Rover vehicles — Range Rover, Discovery, Defender — are a significant presence in the North and West Leeds areas. JLR (Jaguar Land Rover) uses a proprietary Key Vehicle Module (KVM) system that is among the most security-conscious of any UK brand. We carry JLR-compatible programming tools for all Land Rover models sold in the UK from 2005 onward.",
    keyTech: "Land Rover uses the Key Vehicle Module (KVM) system across all current models. Older models (Freelander 2, Discovery 3/4, Range Rover Sport L320) use a Hitachi-based KVM requiring pin-code extraction via the KVM EEPROM. Current Defender (L663), Discovery (L462), Range Rover (L405/L460), and Range Rover Sport (L461) use the latest Jaguar Land Rover EWS4/SDD-level programming with JLR-specific DOIP diagnostics. Smart key and keyless entry are standard on all current Land Rover models. All-keys-lost Land Rover is a specialised job requiring JLR SDD/IDS diagnostic interface — we carry the required equipment and perform all work on-site.",
    models: ['Land Rover Defender', 'Land Rover Discovery', 'Land Rover Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar', 'Land Rover Freelander'],
    pricingRows: [
      ['Land Rover key fob (older KVM — Freelander 2, Discovery 3/4)', '£160 – £250'],
      ['Land Rover smart key (current Defender/Discovery/Range Rover)', '£250 – £380'],
      ['Land Rover lockout — emergency access', '£90 – £140'],
      ['Land Rover spare key (with original present)', '£160 – £300'],
    ],
    faqs: [
      { q: 'How much does a Land Rover key replacement cost in Leeds?', a: "Land Rover key costs are among the higher end in the industry due to the JLR KVM system's complexity. Older models (Freelander 2, Discovery 3/4 KVM): £160–£250. Current Defender, Discovery 5, Range Rover L405/L460 smart key: £250–£380. We quote precisely over the phone based on your model, year, and VIN." },
      { q: 'Can you replace a Land Rover key without going to a JLR dealer?', a: "Yes — though Land Rover keys are among the most complex we handle. JLR dealer key replacement starts at £500 for older models and can reach £800+ for current Range Rover smart keys. We carry the JLR SDD/IDS-compatible interface and perform the full KVM programming procedure at your location. No recovery truck required." },
      { q: 'What is the Land Rover KVM system?', a: "KVM stands for Key Vehicle Module — a dedicated security ECU in Land Rover vehicles that manages key authentication, rolling-code verification, and immobiliser functions. Every new key must be paired to the KVM. On older models, this requires EEPROM extraction of the KVM module. On current models, JLR DOIP diagnostic-level access is required. We carry equipment for both generations." },
      { q: 'Do you cover the current Land Rover Defender (L663) key?', a: "Yes. The Defender L663 (2020+) uses JLR's latest smart key with DOIP-level programming. It is the most involved Land Rover key job — expect 75–90 minutes on-site and a cost of £280–£380. We need proof of ownership and VIN before starting." },
      { q: 'Can you help with a Range Rover Sport key in Leeds?', a: "Yes. Range Rover Sport L320 (2005–2013) uses older KVM: £160–£250. L494 (2014–2022) uses newer JLR smart key: £220–£320. L461 (2023+) uses latest JLR DOIP system: £280–£380. All handled on-site." },
      { q: 'Do you cover Land Rover Discovery 3 and 4 key replacement?', a: "Yes. Discovery 3 and 4 use the older Hitachi KVM system — well-understood and handled on-site in 65–80 minutes. Cost: £160–£250. Common call-out in North Leeds where Discovery ownership is higher." },
      { q: 'Can you do an all-keys-lost job on a Land Rover in Leeds?', a: "Yes, but Land Rover all-keys-lost is a specialist job. On older KVM models (Discovery 3/4, Freelander 2), we extract the KVM EEPROM on-site. On current models, JLR SDD access is required to generate a new key token. Expect 80–100 minutes and £280–£420 depending on model. Proof of ownership required." },
      { q: 'How quickly can you reach me with a Land Rover emergency in Leeds?', a: "Response across all Leeds postcodes is 25–45 minutes. North Leeds (Alwoodley, Roundhay, Harrogate Road) — where Land Rover ownership is highest — is a 30–40 minute drive from our base. 24/7." },
    ],
  },
  {
    slug: 'fiat',
    name: 'Fiat',
    metaTitle: 'Fiat Car Key Replacement Leeds | 500 Panda Tipo Doblo | 24/7',
    metaDesc: 'Mobile Fiat key specialist Leeds. 500, Panda, Tipo, Doblo — Fiat CODE chip, flip key programmed on-site. 24/7 fixed price. Call 07309 903243.',
    h1: 'Fiat Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Fiat's 500 is among the most recognisable cars on Leeds city streets, and the Panda and Tipo are common across suburban Leeds. Fiat uses its own proprietary CODE system across most models. We carry Fiat CODE chip blanks and programming tools for all UK-market Fiat models from the 500 to the Doblo.",
    keyTech: "Fiat uses its proprietary CODE (Codice di Difesa Elettronica) immobiliser system. Most current Fiat models use ID48 Megamos Crypto transponders with Fiat-specific OBD pin-code programming. The Fiat 500 (312), Panda (319), and Tipo (356) use a flip remote key with a Fiat-specific blade cut and ID48 transponder. Fiat 500X and 500L share the PSA/Jeep platform and use a different BSI-derived architecture. The Fiat e-500 uses a smart key system on the EV platform. All-keys-lost Fiat requires pin-code extraction via the BCM (Body Control Module) — we carry the Fiat-specific OBD interface.",
    models: ['Fiat 500', 'Fiat 500X', 'Fiat 500L', 'Fiat Panda', 'Fiat Tipo', 'Fiat Doblo', 'Fiat Ducato', 'Fiat Bravo', 'Fiat Punto'],
    pricingRows: [
      ['Fiat transponder / flip key (CODE system)', '£80 – £135'],
      ['Fiat 500X / 500L smart key (PSA platform)', '£140 – £210'],
      ['Fiat e-500 smart key', '£150 – £220'],
      ['Fiat lockout — emergency access', '£60 – £100'],
      ['Fiat Doblo / Ducato van key', '£85 – £150'],
    ],
    faqs: [
      { q: 'How much does a Fiat 500 key replacement cost in Leeds?', a: 'Fiat 500 (312 platform, 2008–2024) uses a flip remote key with Fiat CODE ID48 chip: £80–£135. Fiat e-500 (EV, 2020+) uses a smart key: £150–£220. Confirmed over the phone.' },
      { q: 'Can you replace a Fiat key without a dealer?', a: "Yes. We use Fiat-compatible OBD tools and carry Fiat CODE chip blanks for all UK models. Standard Fiat flip key job: 40–55 minutes on-site. Dealer cost for the equivalent: £220–£360." },
      { q: 'My Fiat 500 flip key has broken — the blade snapped out of the fob — can you fix it?', a: "Yes. Broken flip key blade is a very common Fiat 500 issue. We replace the key shell and blade, retain the existing transponder chip if undamaged, and re-cut the blade. If the chip is also damaged, we programme a new one to the CODE system. Cost starts from £80." },
      { q: 'Is the Fiat 500X key the same as the Fiat 500?', a: "No. The 500X uses a PSA/Jeep Renegade platform with a different key system to the standard 500. The 500X uses a more modern OBD-programmed smart key (£140–£210), not the classic Fiat CODE flip key." },
      { q: 'Do you cover Fiat Doblo and Ducato van keys in Leeds?', a: "Yes. Doblo uses the Fiat CODE system — standard flip remote key, £85–£150. Ducato shares the Peugeot Boxer/Citroën Relay platform and uses PSA BSI architecture. Both are common commercial calls in the Leeds area." },
      { q: 'Can you make a spare Fiat Panda key in Leeds?', a: 'Yes. Panda (319, 312 platform) uses Fiat CODE flip key. Spare with original: £80–£130. Same-day across Leeds.' },
      { q: 'How long does a Fiat key replacement take?', a: 'CODE flip key: 40–55 minutes. Smart key (500X, e-500): 55–70 minutes. All-keys-lost BCM extraction: 60–75 minutes. Response: 25–45 minutes.' },
      { q: 'What proof of ownership do you need for a Fiat key replacement?', a: "V5C logbook, insurance document showing your name and registration, or a finance agreement. For lockouts, driver's licence plus registration document is sufficient." },
    ],
  },
  {
    slug: 'mazda',
    name: 'Mazda',
    metaTitle: 'Mazda Car Key Replacement Leeds | Mazda 3 6 CX-5 CX-30 | 24/7',
    metaDesc: 'Mobile Mazda key specialist Leeds. Mazda 3, 6, CX-5, CX-30 — ID47/ID49, Advanced Keyless Entry programmed on-site. 24/7. Call 07309 903243.',
    h1: 'Mazda Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Mazda ownership is growing across Leeds — particularly the Mazda CX-5 and Mazda 3. Mazda's key systems use specific transponder chip types and a dedicated Advanced Keyless Entry (AKE) system on CX-series and 6 models. We carry Mazda-compatible programming tools and blanks for all UK-market Mazda models.",
    keyTech: "Mazda uses Texas Instruments ID47 transponder chips on most current models (Mazda 3 BP, Mazda 6 GJ, CX-5 KF, CX-30, CX-60) and ID49 on some older models. Mazda's Advanced Keyless Entry (AKE) system — available on CX-5, CX-30, Mazda 6, and all CX-60 variants — uses encrypted rolling-code RF with OBD-level pairing beyond the transponder. All-keys-lost Mazda requires pin-code extraction from the PCM (Powertrain Control Module) or BCM. We carry Mazda-specific IDS-compatible OBD tools for all UK-market generations.",
    models: ['Mazda 2', 'Mazda 3', 'Mazda 6', 'Mazda CX-3', 'Mazda CX-30', 'Mazda CX-5', 'Mazda CX-60', 'Mazda MX-5', 'Mazda MX-30'],
    pricingRows: [
      ['Mazda transponder key (ID47)', '£90 – £150'],
      ['Mazda Advanced Keyless Entry key', '£150 – £230'],
      ['Mazda lockout — emergency access', '£60 – £100'],
      ['Mazda spare key (with original present)', '£90 – £150'],
    ],
    faqs: [
      { q: 'How much does a Mazda CX-5 key replacement cost in Leeds?', a: 'Mazda CX-5 KF (2017+) typically uses Advanced Keyless Entry: £150–£230. Earlier CX-5 KE (2012–2017) uses ID47 standard transponder: £90–£145. Confirmed over the phone based on your model year.' },
      { q: 'Can you replace a Mazda key without a dealer?', a: "Yes. We use Mazda IDS-compatible OBD tools and carry ID47/ID49 blanks for all UK Mazda models. Standard transponder job: 50–65 minutes on-site. Dealer equivalent: £250–£400." },
      { q: 'What is Mazda Advanced Keyless Entry and how does it affect key replacement?', a: "Mazda AKE is a proximity smart key system available on CX-5, CX-30, CX-60, and Mazda 6. It uses an encrypted rolling-code RF frequency in addition to the transponder chip. Programming requires OBD-level pairing with the BCM, beyond just transponder programming. AKE key replacement takes 60–75 minutes versus 50–65 for a standard key." },
      { q: 'Do you cover Mazda MX-5 key replacement in Leeds?', a: "Yes. Mazda MX-5 ND (2015+) uses ID47 transponder key. Cost: £90–£145. The MX-5 NC (2005–2015) uses an older Mazda chip. Both generations covered." },
      { q: 'Can you replace a Mazda CX-60 key in Leeds?', a: "Yes. CX-60 uses Mazda's latest Advanced Keyless Entry system. Smart key: £170–£240. Call with your VIN for a precise quote as the CX-60 has multi-variant key options." },
      { q: 'My Mazda 3 key fob has stopped working after the battery was replaced — why?', a: "After a battery change, Mazda remote keys sometimes need re-syncing. With the key in the ignition (position II), press and hold the lock button for 5 seconds. If this doesn't restore remote function, we re-sync on-site in 20–30 minutes." },
      { q: 'How long does a Mazda key replacement take?', a: 'ID47 transponder key: 50–65 minutes. AKE smart key: 60–75 minutes. All-keys-lost: 65–80 minutes. Response: 25–45 minutes across Leeds.' },
      { q: 'Can you cut a spare Mazda key in Leeds the same day?', a: 'Yes. Spare key with original: £90–£150. Same-day across Leeds for most Mazda models.' },
    ],
  },
  {
    slug: 'volvo',
    name: 'Volvo',
    metaTitle: 'Volvo Car Key Replacement Leeds | XC40 XC60 V40 V60 | 24/7',
    metaDesc: 'Mobile Volvo key specialist Leeds. XC40, XC60, XC90, V40, V60 — CEM module, smart key programmed on-site. 24/7. Call 07309 903243.',
    h1: 'Volvo Car Key Replacement Leeds',
    postcode: 'Leeds',
    intro: "Volvo is well-represented in the North and West Leeds residential areas — XC40 and XC60 are frequent call-outs in Roundhay, Alwoodley, and Horsforth. Volvo uses a Central Electronics Module (CEM) architecture that requires Volvo-specific programming tools for key replacement. We carry the Volvo VIDA/DiCE-compatible interface and key blanks for all current and recent UK-market Volvo models.",
    keyTech: "Volvo uses a Central Electronics Module (CEM) as the central security authority. All key programming must be authorised through the CEM. Older Volvo models (V40 Mk1, S40, V50, XC90 Mk1) use PCC (Personal Car Communicator) keys with Philips ID46 transponders and CEM OBD programming. Current Volvo models (XC40 536, XC60 246, XC90 256, V60 225, V90 236) from 2017 onward use a keyless entry smart key requiring CEM-level PIN authorisation and Volvo Dice/VIDA programming. The Google-based Android Automotive infotainment system on 2021+ Volvos is separate from the key system. We carry Volvo CEM programming adapters and key blanks for all UK-market generations.",
    models: ['Volvo XC40', 'Volvo XC60', 'Volvo XC90', 'Volvo V40', 'Volvo V60', 'Volvo V90', 'Volvo S60', 'Volvo S90', 'Volvo C40'],
    pricingRows: [
      ['Volvo transponder key (older CEM — V50, older XC90)', '£130 – £200'],
      ['Volvo smart key (current XC40/XC60/V60)', '£190 – £290'],
      ['Volvo lockout — emergency access', '£70 – £110'],
      ['Volvo spare key (with original present)', '£130 – £220'],
    ],
    faqs: [
      { q: 'How much does a Volvo XC60 key replacement cost in Leeds?', a: 'Volvo XC60 246 (2017+) uses CEM smart key: £190–£290. Older XC60 156 (2008–2017) uses PCC transponder key: £130–£195. Confirmed over the phone based on your registration and model year.' },
      { q: 'Can you replace a Volvo key without a Volvo dealer?', a: "Yes. Volvo dealer key replacement starts at £450 and can reach £700+ for smart keys. We use Volvo VIDA/DiCE-compatible CEM programming tools and carry Volvo key blanks for all UK generations. Jobs are completed at your location — no towing, no booking delays." },
      { q: 'What is the Volvo CEM module and how does it affect key replacement?', a: "Volvo's CEM (Central Electronics Module) is the master security ECU that authorises every key. New keys cannot be programmed without CEM involvement. For all-keys-lost scenarios, we access the CEM via OBD to extract the stored PIN/CS. On older CEM generations (pre-2017), this is an OBD-level read. On current P3/SPA architecture, VIDA-level authorisation is required." },
      { q: 'Do you cover Volvo XC40 key replacement, including the Recharge EV version?', a: "Yes. The XC40 536 uses the same CEM smart key system regardless of drivetrain. XC40 Recharge: same key, same cost (£190–£290). The EV architecture is separate from the key system." },
      { q: 'Can you replace a Volvo C40 Recharge key in Leeds?', a: "Yes. C40 shares the CMA platform with XC40 and uses an identical key system. Smart key: £190–£290. 24/7 across all Leeds postcodes." },
      { q: 'My Volvo XC90 remote key has stopped working — the buttons don't respond. What should I check?', a: "Replace the CR2025 battery first. If remote functions don't restore, hold the unlock button for 5 seconds inside the car to re-sync the remote. If this fails, the fob RF has de-registered from the CEM — we re-register on-site in 30–40 minutes." },
      { q: 'Do you cover Volvo V60 and V90 keys in Leeds?', a: "Yes. V60 225 (2018+) and V90 236 (2016+) both use CEM smart key system: £190–£290. V40 (2012–2019) uses CEM transponder key: £130–£195. Common North Leeds call-outs." },
      { q: 'How long does a Volvo key replacement take?', a: 'CEM transponder key: 60–75 minutes. Smart key: 65–80 minutes. All-keys-lost with CEM EEPROM: 75–90 minutes. Response across Leeds: 25–45 minutes.' },
    ],
  },
]

export const brandSlugs = brands.map(b => b.slug)
